build:
    image: default-jammy
    environment:
        php:
            version: 8.3.28

        node: 'v18.20'

    dependencies:
        override:
            - composer install --ignore-platform-reqs --no-interaction --no-scripts # disable PHP dependency (pecl modules) installation

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
