name: 'PHP 8.3 PostgreSQL Functional Tests'
description: 'Run PHP 8.3 with PostgreSQL functional tests on Debian with Dynamic Store OFF'

inputs:
  slack_bot_token:
    description: 'Slack bot token for notifications'
    required: true
  weekly_ci_slack_channel_id:
    description: 'Slack channel ID for weekly CI notifications'
    required: true
  jira_ticket_slack_user_group_mapping:
    description: 'JIRA ticket to Slack user group mapping'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run docker
      shell: bash
      run: |
        git clone --depth 1 https://github.com/spryker/docker-sdk.git ./docker
        docker/sdk boot deploy.ci.functional.dynamic-store-off.yml
        docker/sdk up -t
        docker/sdk cli composer dump-autoload -o -a --apcu
        docker/sdk testing codecept run -c codeception.functional.yml
      env:
        PROGRESS_TYPE: plain
        SPRYKER_PLATFORM_IMAGE: spryker/php:8.3-debian
        TRAVIS: 1

    - name: Slack Notification for failed job
      uses: ./.github/actions/job-slack-notifications
      if: always()
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        WEEKLY_CI_SLACK_CHANNEL_ID: ${{ inputs.weekly_ci_slack_channel_id }}
        JIRA_TICKET_SLACK_USER_GROUP_MAPPING: ${{ inputs.jira_ticket_slack_user_group_mapping }}
